[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[forms]
  [forms.contact]
    name = "contact"
    success_url = "/success"

[functions]
  node_bundler = "esbuild"

[build.processing]
  skip_processing = false
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true

# Configurazione per il caricamento dei file
[build.environment]
  MAX_FILE_SIZE = "52428800" # 50MB in bytes 