[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/success"
  to = "/success/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[forms]
  [forms.contact]
    name = "contact"
    success_url = "/success" 